/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppOperiaRouteImport } from './routes/_app/operia'
import { Route as AppLockersRouteImport } from './routes/_app/lockers'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppHandlingClassesRouteImport } from './routes/_app/handling-classes'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDepartmentsRouteImport } from './routes/_app/departments'
import { Route as AppConfigureRouteImport } from './routes/_app/configure'
import { Route as AppCarriersRouteImport } from './routes/_app/carriers'
import { Route as AppParcelsIndexRouteImport } from './routes/_app/parcels.index'
import { Route as AppOperiaIndexRouteImport } from './routes/_app/operia.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AppImportIndexRouteImport } from './routes/_app/import.index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets.index'
import { Route as AppSystemUsersRouteImport } from './routes/_app/system.users'
import { Route as AppSystemLabelTemplatesRouteImport } from './routes/_app/system.label-templates'
import { Route as AppSystemEmailTemplatesRouteImport } from './routes/_app/system.email-templates'
import { Route as AppSystemCompanyRouteImport } from './routes/_app/system.company'
import { Route as AppProductsProductKeyRouteImport } from './routes/_app/products.$productKey'
import { Route as AppPlatformIntegrationsRouteImport } from './routes/_app/platform.integrations'
import { Route as AppPlatformBrandingRouteImport } from './routes/_app/platform.branding'
import { Route as AppPlatformBillingRouteImport } from './routes/_app/platform.billing'
import { Route as AppParcelsReceiveRouteImport } from './routes/_app/parcels.receive'
import { Route as AppParcelsHandoutRouteImport } from './routes/_app/parcels.handout'
import { Route as AppOperiaTemplatesRouteImport } from './routes/_app/operia.templates'
import { Route as AppOperiaShippingRouteImport } from './routes/_app/operia.shipping'
import { Route as AppOperiaProductsRouteImport } from './routes/_app/operia.products'
import { Route as AppOperiaNotificationsRouteImport } from './routes/_app/operia.notifications'
import { Route as AppOperiaLogsRouteImport } from './routes/_app/operia.logs'
import { Route as AppOperiaLocalizationRouteImport } from './routes/_app/operia.localization'
import { Route as AppOperiaCustomersRouteImport } from './routes/_app/operia.customers'
import { Route as AppOperiaCarriersRouteImport } from './routes/_app/operia.carriers'
import { Route as AppOperiaBillingRouteImport } from './routes/_app/operia.billing'
import { Route as AppOperiaAssetsRouteImport } from './routes/_app/operia.assets'
import { Route as AppOperiaApikeysRouteImport } from './routes/_app/operia.apikeys'
import { Route as AppImportRemoteRouteImport } from './routes/_app/import.remote'
import { Route as AppImportLogRouteImport } from './routes/_app/import.log'
import { Route as AppImportLocalRouteImport } from './routes/_app/import.local'
import { Route as AppImportConfigRouteImport } from './routes/_app/import.config'
import { Route as AppConfigureTemplatesRouteImport } from './routes/_app/configure.templates'
import { Route as AppConfigureShippingRouteImport } from './routes/_app/configure.shipping'
import { Route as AppConfigureProductsRouteImport } from './routes/_app/configure.products'
import { Route as AppConfigureNotificationsRouteImport } from './routes/_app/configure.notifications'
import { Route as AppConfigureLogoRouteImport } from './routes/_app/configure.logo'
import { Route as AppConfigureLocalizationRouteImport } from './routes/_app/configure.localization'
import { Route as AppConfigureBillingRouteImport } from './routes/_app/configure.billing'
import { Route as AppConfigureAppearanceRouteImport } from './routes/_app/configure.appearance'
import { Route as AppAssetsLocationsRouteImport } from './routes/_app/assets.locations'
import { Route as AppAssetsCategoriesRouteImport } from './routes/_app/assets.categories'
import { Route as AppInventoryImportItemsRouteImport } from './routes/_app/inventory.import.items'
import { Route as AppInventoryExportItemsRouteImport } from './routes/_app/inventory.export.items'
import { Route as AppAssetsImportAssetsRouteImport } from './routes/_app/assets.import.assets'
import { Route as AppAssetsExportAssetsRouteImport } from './routes/_app/assets.export.assets'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOperiaRoute = AppOperiaRouteImport.update({
  id: '/operia',
  path: '/operia',
  getParentRoute: () => AppRoute,
} as any)
const AppLockersRoute = AppLockersRouteImport.update({
  id: '/lockers',
  path: '/lockers',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppHandlingClassesRoute = AppHandlingClassesRouteImport.update({
  id: '/handling-classes',
  path: '/handling-classes',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigureRoute = AppConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AppRoute,
} as any)
const AppCarriersRoute = AppCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AppRoute,
} as any)
const AppParcelsIndexRoute = AppParcelsIndexRouteImport.update({
  id: '/parcels/',
  path: '/parcels/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperiaIndexRoute = AppOperiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportIndexRoute = AppImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemUsersRoute = AppSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemLabelTemplatesRoute = AppSystemLabelTemplatesRouteImport.update({
  id: '/system/label-templates',
  path: '/system/label-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemEmailTemplatesRoute = AppSystemEmailTemplatesRouteImport.update({
  id: '/system/email-templates',
  path: '/system/email-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemCompanyRoute = AppSystemCompanyRouteImport.update({
  id: '/system/company',
  path: '/system/company',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductKeyRoute = AppProductsProductKeyRouteImport.update({
  id: '/products/$productKey',
  path: '/products/$productKey',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformIntegrationsRoute = AppPlatformIntegrationsRouteImport.update({
  id: '/platform/integrations',
  path: '/platform/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformBrandingRoute = AppPlatformBrandingRouteImport.update({
  id: '/platform/branding',
  path: '/platform/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformBillingRoute = AppPlatformBillingRouteImport.update({
  id: '/platform/billing',
  path: '/platform/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppParcelsReceiveRoute = AppParcelsReceiveRouteImport.update({
  id: '/parcels/receive',
  path: '/parcels/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppParcelsHandoutRoute = AppParcelsHandoutRouteImport.update({
  id: '/parcels/handout',
  path: '/parcels/handout',
  getParentRoute: () => AppRoute,
} as any)
const AppOperiaTemplatesRoute = AppOperiaTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaShippingRoute = AppOperiaShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaProductsRoute = AppOperiaProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaNotificationsRoute = AppOperiaNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaLogsRoute = AppOperiaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaLocalizationRoute = AppOperiaLocalizationRouteImport.update({
  id: '/localization',
  path: '/localization',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaCustomersRoute = AppOperiaCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaCarriersRoute = AppOperiaCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaBillingRoute = AppOperiaBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaAssetsRoute = AppOperiaAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppOperiaApikeysRoute = AppOperiaApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => AppOperiaRoute,
} as any)
const AppImportRemoteRoute = AppImportRemoteRouteImport.update({
  id: '/import/remote',
  path: '/import/remote',
  getParentRoute: () => AppRoute,
} as any)
const AppImportLogRoute = AppImportLogRouteImport.update({
  id: '/import/log',
  path: '/import/log',
  getParentRoute: () => AppRoute,
} as any)
const AppImportLocalRoute = AppImportLocalRouteImport.update({
  id: '/import/local',
  path: '/import/local',
  getParentRoute: () => AppRoute,
} as any)
const AppImportConfigRoute = AppImportConfigRouteImport.update({
  id: '/import/config',
  path: '/import/config',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigureTemplatesRoute = AppConfigureTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppConfigureShippingRoute = AppConfigureShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppConfigureProductsRoute = AppConfigureProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppConfigureNotificationsRoute =
  AppConfigureNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppConfigureRoute,
  } as any)
const AppConfigureLogoRoute = AppConfigureLogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppConfigureLocalizationRoute =
  AppConfigureLocalizationRouteImport.update({
    id: '/localization',
    path: '/localization',
    getParentRoute: () => AppConfigureRoute,
  } as any)
const AppConfigureBillingRoute = AppConfigureBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppConfigureAppearanceRoute = AppConfigureAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppConfigureRoute,
} as any)
const AppAssetsLocationsRoute = AppAssetsLocationsRouteImport.update({
  id: '/assets/locations',
  path: '/assets/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsCategoriesRoute = AppAssetsCategoriesRouteImport.update({
  id: '/assets/categories',
  path: '/assets/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryImportItemsRoute = AppInventoryImportItemsRouteImport.update({
  id: '/inventory/import/items',
  path: '/inventory/import/items',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryExportItemsRoute = AppInventoryExportItemsRouteImport.update({
  id: '/inventory/export/items',
  path: '/inventory/export/items',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsImportAssetsRoute = AppAssetsImportAssetsRouteImport.update({
  id: '/assets/import/assets',
  path: '/assets/import/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsExportAssetsRoute = AppAssetsExportAssetsRouteImport.update({
  id: '/assets/export/assets',
  path: '/assets/export/assets',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/carriers': typeof AppCarriersRoute
  '/configure': typeof AppConfigureRouteWithChildren
  '/departments': typeof AppDepartmentsRoute
  '/employees': typeof AppEmployeesRoute
  '/handling-classes': typeof AppHandlingClassesRoute
  '/locations': typeof AppLocationsRoute
  '/lockers': typeof AppLockersRoute
  '/operia': typeof AppOperiaRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/assets/categories': typeof AppAssetsCategoriesRoute
  '/assets/locations': typeof AppAssetsLocationsRoute
  '/configure/appearance': typeof AppConfigureAppearanceRoute
  '/configure/billing': typeof AppConfigureBillingRoute
  '/configure/localization': typeof AppConfigureLocalizationRoute
  '/configure/logo': typeof AppConfigureLogoRoute
  '/configure/notifications': typeof AppConfigureNotificationsRoute
  '/configure/products': typeof AppConfigureProductsRoute
  '/configure/shipping': typeof AppConfigureShippingRoute
  '/configure/templates': typeof AppConfigureTemplatesRoute
  '/import/config': typeof AppImportConfigRoute
  '/import/local': typeof AppImportLocalRoute
  '/import/log': typeof AppImportLogRoute
  '/import/remote': typeof AppImportRemoteRoute
  '/operia/apikeys': typeof AppOperiaApikeysRoute
  '/operia/assets': typeof AppOperiaAssetsRoute
  '/operia/billing': typeof AppOperiaBillingRoute
  '/operia/carriers': typeof AppOperiaCarriersRoute
  '/operia/customers': typeof AppOperiaCustomersRoute
  '/operia/localization': typeof AppOperiaLocalizationRoute
  '/operia/logs': typeof AppOperiaLogsRoute
  '/operia/notifications': typeof AppOperiaNotificationsRoute
  '/operia/products': typeof AppOperiaProductsRoute
  '/operia/shipping': typeof AppOperiaShippingRoute
  '/operia/templates': typeof AppOperiaTemplatesRoute
  '/parcels/handout': typeof AppParcelsHandoutRoute
  '/parcels/receive': typeof AppParcelsReceiveRoute
  '/platform/billing': typeof AppPlatformBillingRoute
  '/platform/branding': typeof AppPlatformBrandingRoute
  '/platform/integrations': typeof AppPlatformIntegrationsRoute
  '/products/$productKey': typeof AppProductsProductKeyRoute
  '/system/company': typeof AppSystemCompanyRoute
  '/system/email-templates': typeof AppSystemEmailTemplatesRoute
  '/system/label-templates': typeof AppSystemLabelTemplatesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/import/': typeof AppImportIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/operia/': typeof AppOperiaIndexRoute
  '/parcels/': typeof AppParcelsIndexRoute
  '/assets/export/assets': typeof AppAssetsExportAssetsRoute
  '/assets/import/assets': typeof AppAssetsImportAssetsRoute
  '/inventory/export/items': typeof AppInventoryExportItemsRoute
  '/inventory/import/items': typeof AppInventoryImportItemsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/carriers': typeof AppCarriersRoute
  '/configure': typeof AppConfigureRouteWithChildren
  '/departments': typeof AppDepartmentsRoute
  '/employees': typeof AppEmployeesRoute
  '/handling-classes': typeof AppHandlingClassesRoute
  '/locations': typeof AppLocationsRoute
  '/lockers': typeof AppLockersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/': typeof AppIndexRoute
  '/assets/categories': typeof AppAssetsCategoriesRoute
  '/assets/locations': typeof AppAssetsLocationsRoute
  '/configure/appearance': typeof AppConfigureAppearanceRoute
  '/configure/billing': typeof AppConfigureBillingRoute
  '/configure/localization': typeof AppConfigureLocalizationRoute
  '/configure/logo': typeof AppConfigureLogoRoute
  '/configure/notifications': typeof AppConfigureNotificationsRoute
  '/configure/products': typeof AppConfigureProductsRoute
  '/configure/shipping': typeof AppConfigureShippingRoute
  '/configure/templates': typeof AppConfigureTemplatesRoute
  '/import/config': typeof AppImportConfigRoute
  '/import/local': typeof AppImportLocalRoute
  '/import/log': typeof AppImportLogRoute
  '/import/remote': typeof AppImportRemoteRoute
  '/operia/apikeys': typeof AppOperiaApikeysRoute
  '/operia/assets': typeof AppOperiaAssetsRoute
  '/operia/billing': typeof AppOperiaBillingRoute
  '/operia/carriers': typeof AppOperiaCarriersRoute
  '/operia/customers': typeof AppOperiaCustomersRoute
  '/operia/localization': typeof AppOperiaLocalizationRoute
  '/operia/logs': typeof AppOperiaLogsRoute
  '/operia/notifications': typeof AppOperiaNotificationsRoute
  '/operia/products': typeof AppOperiaProductsRoute
  '/operia/shipping': typeof AppOperiaShippingRoute
  '/operia/templates': typeof AppOperiaTemplatesRoute
  '/parcels/handout': typeof AppParcelsHandoutRoute
  '/parcels/receive': typeof AppParcelsReceiveRoute
  '/platform/billing': typeof AppPlatformBillingRoute
  '/platform/branding': typeof AppPlatformBrandingRoute
  '/platform/integrations': typeof AppPlatformIntegrationsRoute
  '/products/$productKey': typeof AppProductsProductKeyRoute
  '/system/company': typeof AppSystemCompanyRoute
  '/system/email-templates': typeof AppSystemEmailTemplatesRoute
  '/system/label-templates': typeof AppSystemLabelTemplatesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/assets': typeof AppAssetsIndexRoute
  '/import': typeof AppImportIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/operia': typeof AppOperiaIndexRoute
  '/parcels': typeof AppParcelsIndexRoute
  '/assets/export/assets': typeof AppAssetsExportAssetsRoute
  '/assets/import/assets': typeof AppAssetsImportAssetsRoute
  '/inventory/export/items': typeof AppInventoryExportItemsRoute
  '/inventory/import/items': typeof AppInventoryImportItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/carriers': typeof AppCarriersRoute
  '/_app/configure': typeof AppConfigureRouteWithChildren
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/handling-classes': typeof AppHandlingClassesRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/lockers': typeof AppLockersRoute
  '/_app/operia': typeof AppOperiaRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/categories': typeof AppAssetsCategoriesRoute
  '/_app/assets/locations': typeof AppAssetsLocationsRoute
  '/_app/configure/appearance': typeof AppConfigureAppearanceRoute
  '/_app/configure/billing': typeof AppConfigureBillingRoute
  '/_app/configure/localization': typeof AppConfigureLocalizationRoute
  '/_app/configure/logo': typeof AppConfigureLogoRoute
  '/_app/configure/notifications': typeof AppConfigureNotificationsRoute
  '/_app/configure/products': typeof AppConfigureProductsRoute
  '/_app/configure/shipping': typeof AppConfigureShippingRoute
  '/_app/configure/templates': typeof AppConfigureTemplatesRoute
  '/_app/import/config': typeof AppImportConfigRoute
  '/_app/import/local': typeof AppImportLocalRoute
  '/_app/import/log': typeof AppImportLogRoute
  '/_app/import/remote': typeof AppImportRemoteRoute
  '/_app/operia/apikeys': typeof AppOperiaApikeysRoute
  '/_app/operia/assets': typeof AppOperiaAssetsRoute
  '/_app/operia/billing': typeof AppOperiaBillingRoute
  '/_app/operia/carriers': typeof AppOperiaCarriersRoute
  '/_app/operia/customers': typeof AppOperiaCustomersRoute
  '/_app/operia/localization': typeof AppOperiaLocalizationRoute
  '/_app/operia/logs': typeof AppOperiaLogsRoute
  '/_app/operia/notifications': typeof AppOperiaNotificationsRoute
  '/_app/operia/products': typeof AppOperiaProductsRoute
  '/_app/operia/shipping': typeof AppOperiaShippingRoute
  '/_app/operia/templates': typeof AppOperiaTemplatesRoute
  '/_app/parcels/handout': typeof AppParcelsHandoutRoute
  '/_app/parcels/receive': typeof AppParcelsReceiveRoute
  '/_app/platform/billing': typeof AppPlatformBillingRoute
  '/_app/platform/branding': typeof AppPlatformBrandingRoute
  '/_app/platform/integrations': typeof AppPlatformIntegrationsRoute
  '/_app/products/$productKey': typeof AppProductsProductKeyRoute
  '/_app/system/company': typeof AppSystemCompanyRoute
  '/_app/system/email-templates': typeof AppSystemEmailTemplatesRoute
  '/_app/system/label-templates': typeof AppSystemLabelTemplatesRoute
  '/_app/system/users': typeof AppSystemUsersRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/import/': typeof AppImportIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/operia/': typeof AppOperiaIndexRoute
  '/_app/parcels/': typeof AppParcelsIndexRoute
  '/_app/assets/export/assets': typeof AppAssetsExportAssetsRoute
  '/_app/assets/import/assets': typeof AppAssetsImportAssetsRoute
  '/_app/inventory/export/items': typeof AppInventoryExportItemsRoute
  '/_app/inventory/import/items': typeof AppInventoryImportItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/carriers'
    | '/configure'
    | '/departments'
    | '/employees'
    | '/handling-classes'
    | '/locations'
    | '/lockers'
    | '/operia'
    | '/reports'
    | '/settings'
    | '/stats'
    | '/assets/categories'
    | '/assets/locations'
    | '/configure/appearance'
    | '/configure/billing'
    | '/configure/localization'
    | '/configure/logo'
    | '/configure/notifications'
    | '/configure/products'
    | '/configure/shipping'
    | '/configure/templates'
    | '/import/config'
    | '/import/local'
    | '/import/log'
    | '/import/remote'
    | '/operia/apikeys'
    | '/operia/assets'
    | '/operia/billing'
    | '/operia/carriers'
    | '/operia/customers'
    | '/operia/localization'
    | '/operia/logs'
    | '/operia/notifications'
    | '/operia/products'
    | '/operia/shipping'
    | '/operia/templates'
    | '/parcels/handout'
    | '/parcels/receive'
    | '/platform/billing'
    | '/platform/branding'
    | '/platform/integrations'
    | '/products/$productKey'
    | '/system/company'
    | '/system/email-templates'
    | '/system/label-templates'
    | '/system/users'
    | '/assets/'
    | '/import/'
    | '/inventory/'
    | '/operia/'
    | '/parcels/'
    | '/assets/export/assets'
    | '/assets/import/assets'
    | '/inventory/export/items'
    | '/inventory/import/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/welcome'
    | '/carriers'
    | '/configure'
    | '/departments'
    | '/employees'
    | '/handling-classes'
    | '/locations'
    | '/lockers'
    | '/reports'
    | '/settings'
    | '/stats'
    | '/'
    | '/assets/categories'
    | '/assets/locations'
    | '/configure/appearance'
    | '/configure/billing'
    | '/configure/localization'
    | '/configure/logo'
    | '/configure/notifications'
    | '/configure/products'
    | '/configure/shipping'
    | '/configure/templates'
    | '/import/config'
    | '/import/local'
    | '/import/log'
    | '/import/remote'
    | '/operia/apikeys'
    | '/operia/assets'
    | '/operia/billing'
    | '/operia/carriers'
    | '/operia/customers'
    | '/operia/localization'
    | '/operia/logs'
    | '/operia/notifications'
    | '/operia/products'
    | '/operia/shipping'
    | '/operia/templates'
    | '/parcels/handout'
    | '/parcels/receive'
    | '/platform/billing'
    | '/platform/branding'
    | '/platform/integrations'
    | '/products/$productKey'
    | '/system/company'
    | '/system/email-templates'
    | '/system/label-templates'
    | '/system/users'
    | '/assets'
    | '/import'
    | '/inventory'
    | '/operia'
    | '/parcels'
    | '/assets/export/assets'
    | '/assets/import/assets'
    | '/inventory/export/items'
    | '/inventory/import/items'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/welcome'
    | '/_app/carriers'
    | '/_app/configure'
    | '/_app/departments'
    | '/_app/employees'
    | '/_app/handling-classes'
    | '/_app/locations'
    | '/_app/lockers'
    | '/_app/operia'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/stats'
    | '/_app/'
    | '/_app/assets/categories'
    | '/_app/assets/locations'
    | '/_app/configure/appearance'
    | '/_app/configure/billing'
    | '/_app/configure/localization'
    | '/_app/configure/logo'
    | '/_app/configure/notifications'
    | '/_app/configure/products'
    | '/_app/configure/shipping'
    | '/_app/configure/templates'
    | '/_app/import/config'
    | '/_app/import/local'
    | '/_app/import/log'
    | '/_app/import/remote'
    | '/_app/operia/apikeys'
    | '/_app/operia/assets'
    | '/_app/operia/billing'
    | '/_app/operia/carriers'
    | '/_app/operia/customers'
    | '/_app/operia/localization'
    | '/_app/operia/logs'
    | '/_app/operia/notifications'
    | '/_app/operia/products'
    | '/_app/operia/shipping'
    | '/_app/operia/templates'
    | '/_app/parcels/handout'
    | '/_app/parcels/receive'
    | '/_app/platform/billing'
    | '/_app/platform/branding'
    | '/_app/platform/integrations'
    | '/_app/products/$productKey'
    | '/_app/system/company'
    | '/_app/system/email-templates'
    | '/_app/system/label-templates'
    | '/_app/system/users'
    | '/_app/assets/'
    | '/_app/import/'
    | '/_app/inventory/'
    | '/_app/operia/'
    | '/_app/parcels/'
    | '/_app/assets/export/assets'
    | '/_app/assets/import/assets'
    | '/_app/inventory/export/items'
    | '/_app/inventory/import/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operia': {
      id: '/_app/operia'
      path: '/operia'
      fullPath: '/operia'
      preLoaderRoute: typeof AppOperiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lockers': {
      id: '/_app/lockers'
      path: '/lockers'
      fullPath: '/lockers'
      preLoaderRoute: typeof AppLockersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handling-classes': {
      id: '/_app/handling-classes'
      path: '/handling-classes'
      fullPath: '/handling-classes'
      preLoaderRoute: typeof AppHandlingClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configure': {
      id: '/_app/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof AppConfigureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carriers': {
      id: '/_app/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AppCarriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parcels/': {
      id: '/_app/parcels/'
      path: '/parcels'
      fullPath: '/parcels/'
      preLoaderRoute: typeof AppParcelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operia/': {
      id: '/_app/operia/'
      path: '/'
      fullPath: '/operia/'
      preLoaderRoute: typeof AppOperiaIndexRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/': {
      id: '/_app/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AppImportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/users': {
      id: '/_app/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AppSystemUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/label-templates': {
      id: '/_app/system/label-templates'
      path: '/system/label-templates'
      fullPath: '/system/label-templates'
      preLoaderRoute: typeof AppSystemLabelTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/email-templates': {
      id: '/_app/system/email-templates'
      path: '/system/email-templates'
      fullPath: '/system/email-templates'
      preLoaderRoute: typeof AppSystemEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/company': {
      id: '/_app/system/company'
      path: '/system/company'
      fullPath: '/system/company'
      preLoaderRoute: typeof AppSystemCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productKey': {
      id: '/_app/products/$productKey'
      path: '/products/$productKey'
      fullPath: '/products/$productKey'
      preLoaderRoute: typeof AppProductsProductKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/integrations': {
      id: '/_app/platform/integrations'
      path: '/platform/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof AppPlatformIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/branding': {
      id: '/_app/platform/branding'
      path: '/platform/branding'
      fullPath: '/platform/branding'
      preLoaderRoute: typeof AppPlatformBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/billing': {
      id: '/_app/platform/billing'
      path: '/platform/billing'
      fullPath: '/platform/billing'
      preLoaderRoute: typeof AppPlatformBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parcels/receive': {
      id: '/_app/parcels/receive'
      path: '/parcels/receive'
      fullPath: '/parcels/receive'
      preLoaderRoute: typeof AppParcelsReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parcels/handout': {
      id: '/_app/parcels/handout'
      path: '/parcels/handout'
      fullPath: '/parcels/handout'
      preLoaderRoute: typeof AppParcelsHandoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operia/templates': {
      id: '/_app/operia/templates'
      path: '/templates'
      fullPath: '/operia/templates'
      preLoaderRoute: typeof AppOperiaTemplatesRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/shipping': {
      id: '/_app/operia/shipping'
      path: '/shipping'
      fullPath: '/operia/shipping'
      preLoaderRoute: typeof AppOperiaShippingRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/products': {
      id: '/_app/operia/products'
      path: '/products'
      fullPath: '/operia/products'
      preLoaderRoute: typeof AppOperiaProductsRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/notifications': {
      id: '/_app/operia/notifications'
      path: '/notifications'
      fullPath: '/operia/notifications'
      preLoaderRoute: typeof AppOperiaNotificationsRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/logs': {
      id: '/_app/operia/logs'
      path: '/logs'
      fullPath: '/operia/logs'
      preLoaderRoute: typeof AppOperiaLogsRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/localization': {
      id: '/_app/operia/localization'
      path: '/localization'
      fullPath: '/operia/localization'
      preLoaderRoute: typeof AppOperiaLocalizationRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/customers': {
      id: '/_app/operia/customers'
      path: '/customers'
      fullPath: '/operia/customers'
      preLoaderRoute: typeof AppOperiaCustomersRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/carriers': {
      id: '/_app/operia/carriers'
      path: '/carriers'
      fullPath: '/operia/carriers'
      preLoaderRoute: typeof AppOperiaCarriersRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/billing': {
      id: '/_app/operia/billing'
      path: '/billing'
      fullPath: '/operia/billing'
      preLoaderRoute: typeof AppOperiaBillingRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/assets': {
      id: '/_app/operia/assets'
      path: '/assets'
      fullPath: '/operia/assets'
      preLoaderRoute: typeof AppOperiaAssetsRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/operia/apikeys': {
      id: '/_app/operia/apikeys'
      path: '/apikeys'
      fullPath: '/operia/apikeys'
      preLoaderRoute: typeof AppOperiaApikeysRouteImport
      parentRoute: typeof AppOperiaRoute
    }
    '/_app/import/remote': {
      id: '/_app/import/remote'
      path: '/import/remote'
      fullPath: '/import/remote'
      preLoaderRoute: typeof AppImportRemoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/log': {
      id: '/_app/import/log'
      path: '/import/log'
      fullPath: '/import/log'
      preLoaderRoute: typeof AppImportLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/local': {
      id: '/_app/import/local'
      path: '/import/local'
      fullPath: '/import/local'
      preLoaderRoute: typeof AppImportLocalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import/config': {
      id: '/_app/import/config'
      path: '/import/config'
      fullPath: '/import/config'
      preLoaderRoute: typeof AppImportConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configure/templates': {
      id: '/_app/configure/templates'
      path: '/templates'
      fullPath: '/configure/templates'
      preLoaderRoute: typeof AppConfigureTemplatesRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/shipping': {
      id: '/_app/configure/shipping'
      path: '/shipping'
      fullPath: '/configure/shipping'
      preLoaderRoute: typeof AppConfigureShippingRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/products': {
      id: '/_app/configure/products'
      path: '/products'
      fullPath: '/configure/products'
      preLoaderRoute: typeof AppConfigureProductsRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/notifications': {
      id: '/_app/configure/notifications'
      path: '/notifications'
      fullPath: '/configure/notifications'
      preLoaderRoute: typeof AppConfigureNotificationsRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/logo': {
      id: '/_app/configure/logo'
      path: '/logo'
      fullPath: '/configure/logo'
      preLoaderRoute: typeof AppConfigureLogoRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/localization': {
      id: '/_app/configure/localization'
      path: '/localization'
      fullPath: '/configure/localization'
      preLoaderRoute: typeof AppConfigureLocalizationRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/billing': {
      id: '/_app/configure/billing'
      path: '/billing'
      fullPath: '/configure/billing'
      preLoaderRoute: typeof AppConfigureBillingRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/configure/appearance': {
      id: '/_app/configure/appearance'
      path: '/appearance'
      fullPath: '/configure/appearance'
      preLoaderRoute: typeof AppConfigureAppearanceRouteImport
      parentRoute: typeof AppConfigureRoute
    }
    '/_app/assets/locations': {
      id: '/_app/assets/locations'
      path: '/assets/locations'
      fullPath: '/assets/locations'
      preLoaderRoute: typeof AppAssetsLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/categories': {
      id: '/_app/assets/categories'
      path: '/assets/categories'
      fullPath: '/assets/categories'
      preLoaderRoute: typeof AppAssetsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/import/items': {
      id: '/_app/inventory/import/items'
      path: '/inventory/import/items'
      fullPath: '/inventory/import/items'
      preLoaderRoute: typeof AppInventoryImportItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/export/items': {
      id: '/_app/inventory/export/items'
      path: '/inventory/export/items'
      fullPath: '/inventory/export/items'
      preLoaderRoute: typeof AppInventoryExportItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/import/assets': {
      id: '/_app/assets/import/assets'
      path: '/assets/import/assets'
      fullPath: '/assets/import/assets'
      preLoaderRoute: typeof AppAssetsImportAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/export/assets': {
      id: '/_app/assets/export/assets'
      path: '/assets/export/assets'
      fullPath: '/assets/export/assets'
      preLoaderRoute: typeof AppAssetsExportAssetsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppConfigureRouteChildren {
  AppConfigureAppearanceRoute: typeof AppConfigureAppearanceRoute
  AppConfigureBillingRoute: typeof AppConfigureBillingRoute
  AppConfigureLocalizationRoute: typeof AppConfigureLocalizationRoute
  AppConfigureLogoRoute: typeof AppConfigureLogoRoute
  AppConfigureNotificationsRoute: typeof AppConfigureNotificationsRoute
  AppConfigureProductsRoute: typeof AppConfigureProductsRoute
  AppConfigureShippingRoute: typeof AppConfigureShippingRoute
  AppConfigureTemplatesRoute: typeof AppConfigureTemplatesRoute
}

const AppConfigureRouteChildren: AppConfigureRouteChildren = {
  AppConfigureAppearanceRoute: AppConfigureAppearanceRoute,
  AppConfigureBillingRoute: AppConfigureBillingRoute,
  AppConfigureLocalizationRoute: AppConfigureLocalizationRoute,
  AppConfigureLogoRoute: AppConfigureLogoRoute,
  AppConfigureNotificationsRoute: AppConfigureNotificationsRoute,
  AppConfigureProductsRoute: AppConfigureProductsRoute,
  AppConfigureShippingRoute: AppConfigureShippingRoute,
  AppConfigureTemplatesRoute: AppConfigureTemplatesRoute,
}

const AppConfigureRouteWithChildren = AppConfigureRoute._addFileChildren(
  AppConfigureRouteChildren,
)

interface AppOperiaRouteChildren {
  AppOperiaApikeysRoute: typeof AppOperiaApikeysRoute
  AppOperiaAssetsRoute: typeof AppOperiaAssetsRoute
  AppOperiaBillingRoute: typeof AppOperiaBillingRoute
  AppOperiaCarriersRoute: typeof AppOperiaCarriersRoute
  AppOperiaCustomersRoute: typeof AppOperiaCustomersRoute
  AppOperiaLocalizationRoute: typeof AppOperiaLocalizationRoute
  AppOperiaLogsRoute: typeof AppOperiaLogsRoute
  AppOperiaNotificationsRoute: typeof AppOperiaNotificationsRoute
  AppOperiaProductsRoute: typeof AppOperiaProductsRoute
  AppOperiaShippingRoute: typeof AppOperiaShippingRoute
  AppOperiaTemplatesRoute: typeof AppOperiaTemplatesRoute
  AppOperiaIndexRoute: typeof AppOperiaIndexRoute
}

const AppOperiaRouteChildren: AppOperiaRouteChildren = {
  AppOperiaApikeysRoute: AppOperiaApikeysRoute,
  AppOperiaAssetsRoute: AppOperiaAssetsRoute,
  AppOperiaBillingRoute: AppOperiaBillingRoute,
  AppOperiaCarriersRoute: AppOperiaCarriersRoute,
  AppOperiaCustomersRoute: AppOperiaCustomersRoute,
  AppOperiaLocalizationRoute: AppOperiaLocalizationRoute,
  AppOperiaLogsRoute: AppOperiaLogsRoute,
  AppOperiaNotificationsRoute: AppOperiaNotificationsRoute,
  AppOperiaProductsRoute: AppOperiaProductsRoute,
  AppOperiaShippingRoute: AppOperiaShippingRoute,
  AppOperiaTemplatesRoute: AppOperiaTemplatesRoute,
  AppOperiaIndexRoute: AppOperiaIndexRoute,
}

const AppOperiaRouteWithChildren = AppOperiaRoute._addFileChildren(
  AppOperiaRouteChildren,
)

interface AppRouteChildren {
  AppCarriersRoute: typeof AppCarriersRoute
  AppConfigureRoute: typeof AppConfigureRouteWithChildren
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppHandlingClassesRoute: typeof AppHandlingClassesRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppLockersRoute: typeof AppLockersRoute
  AppOperiaRoute: typeof AppOperiaRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsCategoriesRoute: typeof AppAssetsCategoriesRoute
  AppAssetsLocationsRoute: typeof AppAssetsLocationsRoute
  AppImportConfigRoute: typeof AppImportConfigRoute
  AppImportLocalRoute: typeof AppImportLocalRoute
  AppImportLogRoute: typeof AppImportLogRoute
  AppImportRemoteRoute: typeof AppImportRemoteRoute
  AppParcelsHandoutRoute: typeof AppParcelsHandoutRoute
  AppParcelsReceiveRoute: typeof AppParcelsReceiveRoute
  AppPlatformBillingRoute: typeof AppPlatformBillingRoute
  AppPlatformBrandingRoute: typeof AppPlatformBrandingRoute
  AppPlatformIntegrationsRoute: typeof AppPlatformIntegrationsRoute
  AppProductsProductKeyRoute: typeof AppProductsProductKeyRoute
  AppSystemCompanyRoute: typeof AppSystemCompanyRoute
  AppSystemEmailTemplatesRoute: typeof AppSystemEmailTemplatesRoute
  AppSystemLabelTemplatesRoute: typeof AppSystemLabelTemplatesRoute
  AppSystemUsersRoute: typeof AppSystemUsersRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppImportIndexRoute: typeof AppImportIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppParcelsIndexRoute: typeof AppParcelsIndexRoute
  AppAssetsExportAssetsRoute: typeof AppAssetsExportAssetsRoute
  AppAssetsImportAssetsRoute: typeof AppAssetsImportAssetsRoute
  AppInventoryExportItemsRoute: typeof AppInventoryExportItemsRoute
  AppInventoryImportItemsRoute: typeof AppInventoryImportItemsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarriersRoute: AppCarriersRoute,
  AppConfigureRoute: AppConfigureRouteWithChildren,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppHandlingClassesRoute: AppHandlingClassesRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppLockersRoute: AppLockersRoute,
  AppOperiaRoute: AppOperiaRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsCategoriesRoute: AppAssetsCategoriesRoute,
  AppAssetsLocationsRoute: AppAssetsLocationsRoute,
  AppImportConfigRoute: AppImportConfigRoute,
  AppImportLocalRoute: AppImportLocalRoute,
  AppImportLogRoute: AppImportLogRoute,
  AppImportRemoteRoute: AppImportRemoteRoute,
  AppParcelsHandoutRoute: AppParcelsHandoutRoute,
  AppParcelsReceiveRoute: AppParcelsReceiveRoute,
  AppPlatformBillingRoute: AppPlatformBillingRoute,
  AppPlatformBrandingRoute: AppPlatformBrandingRoute,
  AppPlatformIntegrationsRoute: AppPlatformIntegrationsRoute,
  AppProductsProductKeyRoute: AppProductsProductKeyRoute,
  AppSystemCompanyRoute: AppSystemCompanyRoute,
  AppSystemEmailTemplatesRoute: AppSystemEmailTemplatesRoute,
  AppSystemLabelTemplatesRoute: AppSystemLabelTemplatesRoute,
  AppSystemUsersRoute: AppSystemUsersRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppImportIndexRoute: AppImportIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppParcelsIndexRoute: AppParcelsIndexRoute,
  AppAssetsExportAssetsRoute: AppAssetsExportAssetsRoute,
  AppAssetsImportAssetsRoute: AppAssetsImportAssetsRoute,
  AppInventoryExportItemsRoute: AppInventoryExportItemsRoute,
  AppInventoryImportItemsRoute: AppInventoryImportItemsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
